### ISSUE TITLE
Why does LLVM_CMAKE_PREFIX_PATH need to be specified explicitly?

### ISSUE THREAD

**Issue by mgorny** [opencollab/llvm-toolchain-integration-test-suite#28]
Unless I'm mistaken, this is something that CMake normally detects on its own (based on `PATH`). Any particular reason it needs to be set explicitly here?

**Comment by serge-sans-paille** [comment]
Do you mean we should use the output of `llvm-config --cmakedir` instead?
It's meant to support non-standard llvm install prefix, but maybe there's a better way?

**Comment by mgorny** [comment]
No. I think the cleanest way is to do `find_package(LLVM)` and find some way to get the package path from there.
