### ISSUE TITLE
tagging

### ISSUE THREAD

**Issue by serge-sans-paille** [opencollab/llvm-toolchain-integration-test-suite#62]
CI system love reliable and reproducible setups. Although we designed CI so that it's portable across LLVM version, it would be great to tag releases, but based on what? maybe a tag every 6 month, say when there's a new llvm release? Something else?

**Comment by sylvestre** [comment]
sounds good!
or we merge this repo in the llvm-project tree

**Comment by serge-sans-paille** [comment]
what's better then? once we stabilize after a new llvm-release?

**Comment by sylvestre** [comment]
we tag at the same time as upstream?

**Comment by serge-sans-paille** [comment]
once we verify it works with upstream. I'm fine with that!

**Comment by serge-sans-paille** [comment]
I'll create a tag for 12.0.1 on current HEAD

**Comment by serge-sans-paille** [comment]
https://github.com/opencollab/llvm-toolchain-integration-test-suite/releases/tag/12.0.1
